"""Event routes — lobby access."""
from __future__ import annotations

from fastapi import APIRouter, Query

from app.api.deps import CurrentUser, DBSession, Redis
from app.core.exceptions import ForbiddenError, NotFoundError
from app.repositories.event_repo import EventRepository
from app.schemas.admin import DashboardResponse
from app.schemas.event import (
    EventCreateRequest,
    EventLobbyResponse,
    StrategyCompassTopicsResponse,
)
from app.services.analytics_service import AnalyticsService
from app.services.event_service import EventService
from app.services.strategy_compass_service import StrategyCompassService

router = APIRouter(prefix="/events", tags=["events"])


@router.get(
    "/{slug}/lobby",
    response_model=EventLobbyResponse,
    summary="Get event lobby",
    description="Returns full lobby data for registered attendees. Requires JWT.",
)
async def get_lobby(
    slug: str,
    user: CurrentUser,
    session: DBSession,
    redis: Redis,
) -> EventLobbyResponse:
    service = EventService(session=session, redis=redis)
    return await service.get_lobby(slug, user.user_id)


@router.post(
    "/",
    response_model=EventLobbyResponse,
    status_code=201,
    summary="Create event (admin)",
)
async def create_event(
    payload: EventCreateRequest,
    user: CurrentUser,
    session: DBSession,
    redis: Redis,
) -> EventLobbyResponse:
    service = EventService(session=session, redis=redis)
    return await service.create_event(payload)


@router.get(
    "/{slug}/strategy-compass-topics",
    response_model=StrategyCompassTopicsResponse,
    summary="Generate strategy compass topics",
    description="Returns randomized AI-in-BFSI wheel topics generated by Gemini, scoped to the attendee's event.",
)
async def get_strategy_compass_topics(
    slug: str,
    user: CurrentUser,
    session: DBSession,
    count: int = Query(default=8, ge=6, le=12),
) -> StrategyCompassTopicsResponse:
    service = StrategyCompassService(session=session)
    return await service.get_topics(
        slug=slug,
        user_event_id=user.event_id,
        count=count,
    )


@router.get(
    "/{slug}/dashboard",
    response_model=DashboardResponse,
    summary="Get event dashboard metrics",
    description="Returns live dashboard stats for the attendee's event.",
)
async def get_event_dashboard(
    slug: str,
    user: CurrentUser,
    session: DBSession,
    redis: Redis,
) -> DashboardResponse:
    event_repo = EventRepository(session)
    event = await event_repo.get_by_slug(slug)
    if not event:
        raise NotFoundError(f"Event '{slug}' not found")
    if event.id != user.event_id:
        raise ForbiddenError("You are not authorized to access this event")

    service = AnalyticsService(session=session, redis=redis)
    return await service.get_dashboard(event.id)
